// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6em3FwMUHLS8mzHFh5HXDxH_IzDgmKDE',
    appId: '1:1036323540997:web:026572103fea96b2f10c6c',
    messagingSenderId: '1036323540997',
    projectId: 'flutter-material3',
    authDomain: 'flutter-material3.firebaseapp.com',
    storageBucket: 'flutter-material3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9j6nDer7psFJOAMzv0qXCgxS0l_jxfU8',
    appId: '1:1036323540997:android:d316b0d6aae9807af10c6c',
    messagingSenderId: '1036323540997',
    projectId: 'flutter-material3',
    storageBucket: 'flutter-material3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-oqmPbOhkBJPuJktZN-8Eh1i9guGKZw',
    appId: '1:1036323540997:ios:e4d0bbe79f201cd8f10c6c',
    messagingSenderId: '1036323540997',
    projectId: 'flutter-material3',
    storageBucket: 'flutter-material3.appspot.com',
    iosBundleId: 'com.example.flutterMaterial3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-oqmPbOhkBJPuJktZN-8Eh1i9guGKZw',
    appId: '1:1036323540997:ios:e4d0bbe79f201cd8f10c6c',
    messagingSenderId: '1036323540997',
    projectId: 'flutter-material3',
    storageBucket: 'flutter-material3.appspot.com',
    iosBundleId: 'com.example.flutterMaterial3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6em3FwMUHLS8mzHFh5HXDxH_IzDgmKDE',
    appId: '1:1036323540997:web:924f4d23c9646ccff10c6c',
    messagingSenderId: '1036323540997',
    projectId: 'flutter-material3',
    authDomain: 'flutter-material3.firebaseapp.com',
    storageBucket: 'flutter-material3.appspot.com',
  );

}